# Generated by Django 5.1 on 2024-08-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_artikel_bilder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='bilder',
            field=models.ImageField(blank=True, null=True, upload_to='produkte/'),
        ),
    ]
