# Generated by Django 5.1 on 2024-08-24 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_artikel_bilder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artikel',
            old_name='bilder',
            new_name='bild',
        ),
    ]
