# Generated by Django 5.1 on 2024-08-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_bilder_artikel_bild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='preis',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
